import { Router } from 'express';

import { activityLogRouter } from './activityLog.routes';
import { adminDashboardRouter } from './adminDashboard.routes';
import { adminInsightsRouter } from './adminInsights.routes';
import { adminOpsRouter } from './adminOps.routes';
import { analyticsRouter } from './analytics.routes';
import { announcementRouter } from './announcement.routes';
import { attemptRouter } from './attempt.routes';
import { backupRouter } from './backup.routes';
import { bannerRouter } from './banner.routes';
import { bugReportRouter } from './bugReport.routes';
import { categoryRouter } from './category.routes';
import { certificateRouter } from './certificate.routes';
import { changePasswordRouter } from './changePassword.routes';
import { contentReportRouter } from './contentReport.routes';
import { courseRouter } from './course.routes';
import { dashboardRouter } from './dashboard.routes';
import { databaseRouter } from './database.routes';
import { devicePushRouter } from './devicePush.routes';
import { faqRouter } from './faq.routes';
import { feedbackRouter } from './feedback.routes';
import { feedbackDashboardRouter } from './feedbackDashboard.routes';
import { healthRouter } from './health.routes';
import { leaderboardRouter } from './leaderboard.routes';
import { liveClassRouter } from './liveClass.routes';
import { monitoringRouter } from './monitoring.routes';
import { myCourseRouter } from './myCourse.routes';
import { noteRouter } from './note.routes';
import { notificationRouter } from './notification.routes';
import { paymentRouter } from './payment.routes';
import { pdfRouter } from './pdf.routes';
import { profileRouter } from './profile.routes';
import { profileExtrasRouter } from './profileExtras.routes';
import { questionRouter } from './question.routes';
import { rbacRouter } from './rbac.routes';
import { reminderRouter } from './reminder.routes';
import { reviewRouter } from './review.routes';
import { staffAuthRouter } from './staffAuth.routes';
import { studentAdminRouter } from './studentAdmin.routes';
import { supportChatRouter } from './supportChat.routes';
import { systemOpsRouter } from './systemOps.routes';
import { systemSettingsRouter } from './systemSettings.routes';
import { teacherRouter } from './teacher.routes';
import { testRouter } from './test.routes';
import { videoRouter } from './video.routes';

export const routes = Router();

routes.use('/health', healthRouter);
routes.use(systemOpsRouter);
routes.use(databaseRouter);
routes.use(staffAuthRouter);
routes.use(systemSettingsRouter);
routes.use(devicePushRouter);
routes.use(notificationRouter);
routes.use(reminderRouter);
routes.use(activityLogRouter);
routes.use(monitoringRouter);
routes.use(backupRouter);
routes.use(rbacRouter);
routes.use(profileRouter);
routes.use(profileExtrasRouter);
routes.use(changePasswordRouter);
routes.use(certificateRouter);
routes.use(reviewRouter);
routes.use(feedbackRouter);
routes.use(feedbackDashboardRouter);
routes.use(bugReportRouter);
routes.use(contentReportRouter);
routes.use(faqRouter);
routes.use(supportChatRouter);
routes.use(studentAdminRouter);
routes.use(dashboardRouter);
routes.use(courseRouter);
routes.use(myCourseRouter);
routes.use(videoRouter);
routes.use(pdfRouter);
routes.use(noteRouter);
routes.use(liveClassRouter);
routes.use(testRouter);
routes.use(questionRouter);
routes.use(attemptRouter);
routes.use(leaderboardRouter);
routes.use(analyticsRouter);
routes.use(adminDashboardRouter);
routes.use(adminOpsRouter);
routes.use(adminInsightsRouter);
routes.use(paymentRouter);
routes.use(bannerRouter);
routes.use(announcementRouter);
routes.use(categoryRouter);
routes.use(teacherRouter);

